language: php

addons:
  ssh_known_hosts:
  - doulos.iakob.com

script:
  -

before_deploy:
- openssl aes-256-cbc -K $encrypted_4a3da0747bd3_key -iv $encrypted_4a3da0747bd3_iv
  -in .travis/deploy.pem.enc -out deploy.pem -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.pem
- ssh-add .travis/deploy.pem
- git remote add deploy doulos.iakob.com
- git config --global push.default simple

deploy:
  - provider: script
    skip_cleanup: true
    script: git push deploy master
    on:
      branch: master

